Nuoma/Nuoma/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('book/', include('booking.urls', namespace='booking')),
    path('', include('rooms.urls', namespace='rooms')),
    # for gmail and facebook
    path('social-auth/',include('social_django.urls', namespace='social')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Nuoma/booking/urls.py
from django.urls import path
from . import views

app_name = 'booking'

urlpatterns = [
    path('booking/<int:room_id>/', views.reservation_create, name='reservation_create'),
    path('calendar/', views.show_calendar, name='my_calender'),
    # path('add/<int:room_id>/', views.cart_add, name='cart_add'),
    path('update/<int:res_id>/', views.update_status, name='update_status'),
    path('paided/<int:res_id>/', views.update_status_paid, name='update_status_paid'),
    path('testmail/', views. test_share, name=' test_share')
]

Nuoma/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:room_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:room_id>/', views.cart_remove, name='cart_remove'),
]

Nuoma/rooms/urls.py
from django.urls import path
from . import views

app_name = 'rooms'

urlpatterns = [
    path('', views.room_list, name= 'room_list'),
    path('<slug:category_slug>/', views.room_list, name='room_list_by_category'),
    path('<int:id>/<slug:slug>/', views.room_detail, name='room_detail'),

]

Nuoma/rooms/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('title',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('rooms:room_list_by_category', args=[self.slug])


class Property(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    description = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.title


class Room(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='rooms',
                                 on_delete=models.CASCADE)
    title = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    visible = models.BooleanField(default=False)
    properties1 = models.ManyToManyField(Property, null = True)
    first_image = models.ImageField(upload_to='room/first/', null=True)

    class Meta:
        ordering = ('title',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('rooms:room_detail',
                       args=[self.id, self.slug])

class RoomImage(models.Model):
    image = models.ImageField(upload_to='room/')
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=150, blank=True)
    order = models.PositiveBigIntegerField(null=True)
    room = models.ForeignKey(Room, default=None, related_name='images', on_delete=models.PROTECT)


    def __str__(self):
        return self.title

Nuoma/cart/forms.py
from django import forms


class CartAddRoomForm(forms.Form):

    start_day = forms.DateField(input_formats=['%Y-%m-%d'])
    end_day = forms.DateField(input_formats=['%Y-%m-%d'])

Nuoma/rooms/views.py
from django.shortcuts import render, get_object_or_404
from rooms.models import Room, Category, RoomImage
from booking.forms import AddReserveDayForm, ReservationForm


def get_room_id(object):
    list_id = []
    for item in object:
      list_id.append(item.id)
    return list_id


def room_list(request, category_slug=None):
    category = None

    categories = Category.objects.all()
    rooms = Room.objects.filter(visible=True)
    imag = RoomImage.objects.all()

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        rooms = Room.objects.filter(category=category,  visible=True)

    return render(request,
                  'hotel/rooms/list.html',
                  {'category': category,
                   'categories': categories,
                   'rooms': rooms})


def room_detail(request, id, slug):

    room = get_object_or_404(Room,
                             id=id,
                             slug=slug,
                             visible=True)
    # i6saugoti sesion Id
    imags = RoomImage.objects.filter(room_id=room.id)
    prop = room.properties1.all()
    reservation_days = AddReserveDayForm()

    un_lst = "2021-04-18,2021-04-22,2021-04-23"

    # roomas =request.session.get('room_id')
    # request.session['roomas'] =id
    #
    # print('kambario id', roomas)

    return render(request,
                  'hotel/rooms/detail.html',
                  {'room': room,
                   'imags': imags,
                   'reservation_days': reservation_days,
                   'prop': prop,
                   'mydate': un_lst
                   })

Nuoma/rooms/templates/hotel/rooms/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ room.title }}{% else %}Rooms{% endif %}
{% endblock %}
    {% block header %}
     <link  href="{% static 'hotel-datepicker-4.0.0/dist/css/hotel-datepicker.css' %} " rel="stylesheet">
    {% endblock %}

{% block content %}
    <div class="room-detail">

       <div class="room-datail-image">
             <img src="{% if room.first_image %}{{ room.first_image.url }}{% else %}
              {% static "img/no_image.png" %}{% endif %}">
       </div>

        <h2>{{ room.title }}</h2>
        <h3>
            <a href="{{ room.category.get_absolute_url }}">
                {{ room.category }}
            </a>
        </h3>

        <p class="price">{{ room.price }}</p>
          {{ room.description|linebreaks }}
        {% for property in prop %}
            <ul>  {{ property }} </ul>
        {% endfor %}
    </div>
          <div>
             <form action=" {% url 'booking:reservation_create' room.id %}" method="post">
                {{ reservation_days }}
                {% csrf_token %}
{#                 {% if request.GET.next %}#}
{#                 <input type="hidden" name="next" value="{{ request.GET.next }}" />#}
{#            {% endif %}#}
                <input type="submit" value="Pasirinkite">
            </form>

          </div>


{#  {{mydate}}#}



<script>

let  not_available = '{{ mydate }}'
let fLen = not_available.length;
let not_dates =['2021-04-21'];
not_dates = not_available


const fruits = not_available.split(',');


let no_available = [
        '2021-04-12',
        '2021-04-19',
        '2021-04-22',
        '2021-05-02']
document.write(fruits)
let input = document.getElementById('id_date_range');
let datepicker = new HotelDatepicker(input, {
     disabledDates: fruits,
     enableCheckout: true
});

</script>

<!-- <script>-->
<!-- $(document).ready(function () {-->


<!--      let not_available = '{{ mydate }}'-->

<!--      let dateFormat = "yy-mm-dd",-->
<!--       from = $( "#id_start_day" )-->
<!--          .datepicker({-->
<!--            defaultDate: "+1w",-->
<!--            changeMonth: true,-->
<!--            numberOfMonths: 2,-->
<!--            dateFormat: "yy-mm-dd",-->
<!--             constrainInput: true,-->
<!--               minDate: '2',-->

<!--            beforeShowDay: function (date) {-->
<!--                  let  day = date.getDay();-->
<!--                  let formattedDate = jQuery.datepicker.formatDate("yy-mm-dd", date)-->
<!--                  if (not_available.indexOf(formattedDate) == -1)-->
<!--                  {-->

<!--                            return [true,(not_available.indexOf(formattedDate) == -1)?"":"markholiday"];-->
<!--                  }-->
<!--                  else-->
<!--                          {-->
<!--                              return [false, "markholiday"];-->
<!--                          }-->
<!--              }-->
<!--          })-->
<!--          .on( "change", function() {-->
<!--        to.datepicker( "option", "minDate", getDate( this ) );-->
<!--      }),-->
<!--      //     to-->
<!--       to = $( "#id_end_day" ).datepicker({-->
<!--          defaultDate: "+1w",-->
<!--          changeMonth: true,-->
<!--          numberOfMonths: 2,-->
<!--          dateFormat: "yy-mm-dd",-->

<!--          beforeShowDay: function (date) {-->
<!--              let  day = date.getDay();-->
<!--              let formattedDate = jQuery.datepicker.formatDate("yy-mm-dd", date)-->
<!--              if (not_available.indexOf(formattedDate) == -1)-->
<!--              {-->

<!--                        return [true,(not_available.indexOf(formattedDate) == -1)?"":"markholiday"];-->
<!--              }-->
<!--              else-->
<!--                      {-->
<!--                          return [false, "markholiday"];-->
<!--                      }-->
<!--          }-->
<!--       })-->
<!--       .on( "change", function() {-->
<!--           from.datepicker( "option", "maxDate", getDate( this ) );-->
<!--       });-->

<!--      function getDate( element ) {-->
<!--        let date;-->
<!--        try {-->
<!--          date = $.datepicker.parseDate( dateFormat, element.value );-->
<!--        } catch( error ) {-->
<!--          date = null;-->
<!--        }-->

<!--        return date;-->
<!--      }-->
<!--});-->
<!--    </script>-->


{% endblock %}

Nuoma/rooms/templates/hotel/rooms/list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Rooms{% endif %}
{% endblock %}

{% block content %}
    <div id="sidebar">
        <h3>Categories</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url "rooms:room_list" %}">All</a>
            </li>
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.title }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>

    <div id="main" class="room-list">
    <h1>{% if category %}{{ category.title }}{% else %} Rooms
    {% endif %}</h1>
    {% for room in rooms %}
        <div class="item">
        <a href="{{ room.get_absolute_url }}">
            <img src="{% if room.first_image %}{{ room.first_image.url }}{% else %}
                     {% static 'img/no_image.png' %} {% endif %}"></a>
        <a href="{{ room.get_absolute_url }}">{{ room.title }}</a>

        <br>
        ${{ room.price }}
        </div>
    {% endfor %}
</div>
{% endblock %}