Nuoma/Nuoma/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('book/', include('booking.urls', namespace='booking')),
    path('', include('rooms.urls', namespace='rooms')),
    # for gmail and facebook
    path('social-auth/',include('social_django.urls', namespace='social')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Nuoma/account/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

apps_name = 'account'

urlpatterns = [

    path('', views.dashboard, name='dashboard'),
    path('staff/', views.dashboard, name='staff_dashboard'),
    path('', include('django.contrib.auth.urls')),
    # path('log/', views.login_view, name='custom_login' ),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),

]

Nuoma/booking/urls.py
from django.urls import path
from . import views

app_name = 'booking'

urlpatterns = [
    path('booking/<int:room_id>/', views.reservation_create, name='reservation_create'),
    path('calendar/', views.show_calendar, name='my_calender'),
    # path('add/<int:room_id>/', views.cart_add, name='cart_add'),
    path('update/<int:res_id>/', views.update_status, name='update_status'),
    path('paided/<int:res_id>/', views.update_status_paid, name='update_status_paid'),
    path('testmail/', views. test_share, name=' test_share')
]

Nuoma/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:room_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:room_id>/', views.cart_remove, name='cart_remove'),
]

Nuoma/rooms/urls.py
from django.urls import path
from . import views

app_name = 'rooms'

urlpatterns = [
    path('', views.room_list, name= 'room_list'),
    path('<slug:category_slug>/', views.room_list, name='room_list_by_category'),
    path('<int:id>/<slug:slug>/', views.room_detail, name='room_detail'),

]

Nuoma/account/models.py
from django.db import models
from django.conf import settings
# from django.contrib.auth.models import User
# from django.dispatch import receiver
# from django.db.models.signals import post_save


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone = models.CharField(max_length=25)
    description = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return f'Profile for user {self.user.first_name}'


# @receiver(post_save, sender=User)
# def update_profile_signal(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)
#     instance.profile.save()

Nuoma/account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                                widget=forms.PasswordInput)
    phone = forms.CharField(max_length=20)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']


class UserEditForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ('description', 'phone')


STATUS_CHOICES = (
    ("1", "Patvirtinti"),
    ("2", "Apmoketa"),
    ("-1", "At6aukta"),
    ("4", "Atvyko"),

)
class ChangeStatus(forms.Form):
    reservation_status = forms.TypedChoiceField(choices=STATUS_CHOICES)

Nuoma/account/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from .models import Profile
from booking.models import Reservation
from .forms import UserRegistrationForm, UserEditForm, ProfileEditForm, ChangeStatus
from django.contrib import messages

from django.contrib.auth.forms import AuthenticationForm


#
# def login_view(request):
#     if request.method == 'POST':
#         form = AuthenticationForm(request.POST)
#         if form.is_valid():
#             user = form.get_user()
#             login(request,user)
#             if 'next' in request.POST:
#                 return  redirect(request.POST.get('next'))
#             else:
#                 redirect('dashboard')
#     else:
#         form = AuthenticationForm()
#
#     return render(request, 'registration/login.html', {'form':form})


@login_required
def dashboard(request):
    user = request.user
    profile = get_object_or_404(Profile, user=user)
    reserve = Reservation.objects.filter(user_id=user)

    reserv = Reservation.objects.filter(status='0')
    acepted = Reservation.objects.filter(status='1')
    booked_res = Reservation.objects.filter(status='2')
    form = ChangeStatus()
    if user.is_staff:
        return render(request, 'account/owner_dashboard.html', {'profile': profile,
                                                                'all_build_res': reserv,
                                                                'all_acepted_res': acepted,
                                                                'booked_res': booked_res,
                                                                 'form':form

                                                                })
    else:
        return render(request, 'account/dashboard.html', {'section': 'dashboard',
                                                          'profile': profile,
                                                          'reservations': reserve})


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            profile = Profile(user=new_user)
            profile.phone = user_form.cleaned_data['phone']
            # Profile.objects.create(user=new_user, commit=False)
            profile.save()

            return render(request,
                          'account/register_done.html',
                          {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'account/register.html', {'user_form': user_form})


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated ', 'successfully')
        else:
            messages.error(request, 'Error updating your profile')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request, 'account/edit.html', {'user_form': user_form, 'profile_form': profile_form})

Nuoma/account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
 <!--Let browser know website is optimized for mobile-->
<!--{#      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>#}-->

{#    <link href="{% static 'js/jquery-ui-1.12.1.custom/jquery-ui.css' %}" rel="stylesheet">#}
<!--    <link href="{% static 'js/jquery-ui-1.12.1.custom/jquery-ui.structure.css' %}" rel="stylesheet">-->

{#<!--     <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>-->#}
<!--{#   <script src="{% static 'js/jquery-ui-1.12.1.custom/jquery-ui.min.js' %}"></script>#}-->

     <link  href="{% static 'hotel-datepicker-4.0.0/dist/css/hotel-datepicker.css' %} " rel="stylesheet">
    {% block header %}

    {% endblock %}
    <script src="{% static 'fecha-4.2.1\dist\fecha.min.js' %}"></script>
    <script src="{% static 'hotel-datepicker-4.0.0/dist/js/hotel-datepicker.min.js' %}"></script>



      <style>
        .markholiday .ui-state-default
        {
            background-color:red;
            color: darkblue;
        }
    </style>
</head>
<body>
<div id="header">

    <span class="logo">NUOMA51</span>
    <ul class="menu">

        <li {% if section == "Rooms" %}class="selected"{% endif %}>
            <a href="{% url 'rooms:room_list' %} ">Room List</a>
        </li>

        <li class="selected">
            <a href="{% url 'booking:my_calender' %}"> calender mus</a>
        </li>

        {% if request.user.is_authenticated %}
            <li {% if section == "dashboard" %}class="selected"{% endif %}>
                <a href="{% url 'dashboard' %}"> Tavo užsakymai</a>
            </li>

        {% endif %}

          <span class="user">
                {% if request.user.is_authenticated %}
                    Hello {{ request.user.first_name }},
                    <a href="{% url 'logout' %}">Logout</a>
                {% else %}
{#                     <a href="{% url 'custom_login' %}?next={{request.path}}">Login</a>#}
                    <a href="{% url "login" %}">Log-in</a>
                {% endif %}
          </span>
    </ul>
</div>
    {% if messages %}
        <ul class="messages">
        {% for message in messages %}
               <li class="{{ message.tags }}">
                       {{ message|safe }}
                   <a href="#" class="close">x</a>
               </li>
        {% endfor %}
        </ul>
    {% endif %}
<div>
        {% block content %}
        {% endblock %}

</div>

<!--<script src="{% static 'js/jquery-ui-1.12.1.custom/jquery-ui.min.js' %}"></script>-->

</body>
</html>