Nuoma/Nuoma/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('book/', include('booking.urls', namespace='booking')),
    path('', include('rooms.urls', namespace='rooms')),
    # for gmail and facebook
    path('social-auth/',include('social_django.urls', namespace='social')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Nuoma/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:room_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:room_id>/', views.cart_remove, name='cart_remove'),
]

Nuoma/rooms/urls.py
from django.urls import path
from . import views

app_name = 'rooms'

urlpatterns = [
    path('', views.room_list, name= 'room_list'),
    path('<slug:category_slug>/', views.room_list, name='room_list_by_category'),
    path('<int:id>/<slug:slug>/', views.room_detail, name='room_detail'),

]

Nuoma/cart/forms.py
from django import forms


class CartAddRoomForm(forms.Form):

    start_day = forms.DateField(input_formats=['%Y-%m-%d'])
    end_day = forms.DateField(input_formats=['%Y-%m-%d'])

Nuoma/cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Your shopping cart
{% endblock %}

{% block content %}
    <h1> Jūsų pasirinkti kambariai</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Image</th>
            <th>Kambarys</th>
            <th>Atvykimo diena</th>
            <th>Išvykimo diena</th>
            <th>Remove</th>
            <th>Dienos kaina</th>

        </tr>
        </thead>

        <tbody>
        {% for item in cart %}

            {% with room=item.room %}
                <tr>
                    <td>
                        <a href="{{ room.get_absolute_url }}">
                            <img src="{% if room.first_image %}{{ room.first_image.url }}
                                     {% else %}
                                     {% static 'img/no_image.png' %}
                                  {% endif %}">
                        </a>
                    </td>
                    <td>{{ room.title }}</td>

                    <td>
              <form action="{% url "cart:cart_remove" room.id %}" method="post">
                <input type="submit" value="Remove">
                {% csrf_token %}
              </form>
            </td>

                    <td>{{ item.price }}</td>
                    <td> {{ item.start_day }} </td>
                    <td> {{ item.end_day }} </td>

                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'rooms:room_list' %}" class="button light">Continue shopping</a>
        <a href="#" class="button">Checkout</a>
    </p>
{% endblock %}